app:
  server: 127.0.0.1:3307
  database: haberes
  user: root
  password: root
  add-properties: true
  logging: debug
  livereload:
    enabled: true
    port: 35791
  open-in-view: true
  port: 8091
  mail:
    username: sueldos@um.edu.ar
    password: Daniel22
  tesium:
    server: 127.0.0.1
    port: 8092
    
server:
  port: ${app.port}
  
spring:
  datasource:
    url: jdbc:mysql://${app.server}/${app.database}?useSSL=false&serverTimezone=UTC
    username: ${app.user}
    password: ${app.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: ${app.open-in-view}
    hibernate:
      ddl-auto: none
  devtools:
    livereload:
      enabled: ${app.livereload.enabled}
      port: ${app.livereload.port}
    add-properties: ${app.add-properties}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${app.mail.username}
    password: ${app.mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    um.haberes.rest: DEBUG
    web: ${app.logging}
    org:
      hibernate:
        SQL: ${app.logging}


