package um.haberes.rest.kotlin.internal

import java.math.BigDecimal

data class AfipContext(

    var legajoId: Long?,
    var cuil: String = "",
    var importeDetraer: BigDecimal = BigDecimal.ZERO,
    var baseImponible10: BigDecimal = BigDecimal.ZERO,
    var baseParaElCalculoDiferencialDeContribucionesDeSeguridadSocial: BigDecimal = BigDecimal.ZERO,
    var baseParaElCalculoDiferencialDeAporteDeSeguridadSocial: BigDecimal = BigDecimal.ZERO,
    var baseImponible9: BigDecimal = BigDecimal.ZERO,
    var baseImponible8: BigDecimal = BigDecimal.ZERO,
    var baseImponible7: BigDecimal = BigDecimal.ZERO,
    var baseImponible6: BigDecimal = BigDecimal.ZERO,
    var baseImponible5: BigDecimal = BigDecimal.ZERO,
    var baseImponible4: BigDecimal = BigDecimal.ZERO,
    var baseImponible3: BigDecimal = BigDecimal.ZERO,
    var baseImponible2: BigDecimal = BigDecimal.ZERO,
    var baseImponible1: BigDecimal = BigDecimal.ZERO,
    var remuneracionBruta: BigDecimal = BigDecimal.ZERO,
    var remuneracionMaternidadANSeS: BigDecimal = BigDecimal.ZERO,
    var baseCalculoDiferencialLRT: BigDecimal = BigDecimal.ZERO,
    var baseCalculoDiferencialOSyFSR: BigDecimal = BigDecimal.ZERO,
    var baseCalculoDiferencialAportesOSyFSR: BigDecimal = BigDecimal.ZERO,
    var contribucionAdicionalOS: BigDecimal = BigDecimal.ZERO,
    var aporteAdicionalOS: BigDecimal = BigDecimal.ZERO,
    var cantidadAdherentes: Int = 0,
    var codigoObraSocial: Long = 0,
    var contribucionTareaDiferencial: BigDecimal = BigDecimal.ZERO,
    var porcentajeAporteAdicionalSS: BigDecimal = BigDecimal.ZERO,
    var horasTrabajadas: Int = 0,
    var cantidadDiasTrabajados: Int = 0,
    var diaInicioSituacionRevista3: Int = 0,
    var situacionRevista3: Int = 0,
    var diaInicioSituacionRevista2: Int = 0,
    var situacionRevista2: Int = 0,
    var diaInicioSituacionRevista1: Int = 0,
    var situacionRevista1: Int = 0,
    var codigoLocalidad: Int = 0,
    var codigoSiniestrado: Int = 0,
    var codigoModalidadContratacion: Int = 0,
    var codigoActividad: Int = 0,
    var codigoCondicion: Int = 0,
    var codigoSituacion: Int = 0,
    var tipoOperacion: Int = 0,
    var tipoEmpresa: Int = 0,
    var marcaCorrespondeReduccion: String = "",
    var marcaSCVO: Int = 0,
    var marcaCCT: Int = 0,
    var cantidadHijos: Int = 0,
    var conyuge: Int = 0

) {
    constructor() : this(
        null,
        "",
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        0,
        0,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "",
        0,
        0,
        0,
        0
    )
}